# Generated by Django 3.0.8 on 2020-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_lastname', models.CharField(max_length=50)),
                ('barnach', models.CharField(choices=[('Natural_Scienc', 'Natural_Scienc'), ('Social_Scienc', 'Social_Scienc')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
            ],
        ),
    ]
