# Generated by Django 3.0.8 on 2020-10-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0002_student_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
