# Generated by Django 3.0.8 on 2020-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0003_student_info_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='profile_pic',
            field=models.ImageField(default='images.jpg', null=True, upload_to=''),
        ),
    ]
