# Generated by Django 3.0.8 on 2020-10-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0004_auto_20201007_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='profile_pic',
        ),
    ]
