# Generated by Django 3.0.8 on 2020-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0006_student_info_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='barnach',
            new_name='branch',
        ),
        migrations.AlterField(
            model_name='student_info',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images.jpg', null=True, upload_to=''),
        ),
    ]
