# Generated by Django 3.0.8 on 2020-10-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0007_auto_20201007_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_info',
            name='branch',
            field=models.CharField(blank=True, choices=[('Natural_Scienc', 'Natural_Scienc'), ('Social_Scienc', 'Social_Scienc')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='last_lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
