# Generated by Django 3.0.8 on 2020-10-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0008_auto_20201007_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='Grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
