# Generated by Django 3.0.8 on 2020-10-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0011_student_info_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='user',
        ),
    ]
