# Generated by Django 3.0.8 on 2020-10-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0015_auto_20201015_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('subject', models.CharField(choices=[('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Biology', 'Bilogy'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('English', 'English'), ('Civics', 'Civics'), ('ICT', 'ICT')], max_length=50)),
                ('question', models.TextField()),
                ('dead_line', models.CharField(max_length=50)),
            ],
        ),
    ]
