# Generated by Django 3.0.8 on 2020-10-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0018_assignment_for_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='catagorie',
            field=models.CharField(choices=[('Natural_Scienc', 'Natural_Scienc'), ('Social_Scienc', 'Social_Scienc'), ('Not-student', 'Not-student')], default=False, max_length=50),
        ),
    ]
