# Generated by Django 3.0.8 on 2020-10-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0019_assignment_catagorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submited_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='catagorie',
            field=models.CharField(choices=[('Natural_Scienc', 'Natural_Scienc'), ('Social_Scienc', 'Social_Scienc')], default=None, max_length=50),
        ),
    ]
