# Generated by Django 3.0.8 on 2020-10-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0020_auto_20201018_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='submited_assignment',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='submited_assignment',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='submited_assignment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtoschool.Assignment'),
        ),
    ]
