# Generated by Django 3.0.8 on 2020-10-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0022_auto_20201018_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submited_assignment',
            name='subject',
        ),
    ]
