# Generated by Django 3.0.8 on 2020-10-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0023_remove_submited_assignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='submited_assignment',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Biology', 'Bilogy'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('English', 'English'), ('Civics', 'Civics'), ('ICT', 'ICT')], default=None, max_length=120),
        ),
    ]
