# Generated by Django 3.0.8 on 2020-10-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0024_submited_assignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='submited_assignment',
            name='grade',
            field=models.IntegerField(default=False),
        ),
    ]
