# Generated by Django 3.0.8 on 2020-10-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0027_auto_20201019_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submited_assignment',
            name='grade',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='submited_assignment',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
