# Generated by Django 3.0.8 on 2020-10-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0028_auto_20201019_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submited_assignment',
            name='result',
        ),
        migrations.AlterField(
            model_name='submited_assignment',
            name='first_name',
            field=models.CharField(default=False, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='submited_assignment',
            name='grade',
            field=models.IntegerField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='submited_assignment',
            name='last_name',
            field=models.CharField(default=False, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='submited_assignment',
            name='student_answer',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='submited_assignment',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Biology', 'Bilogy'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('English', 'English'), ('Civics', 'Civics'), ('ICT', 'ICT')], default=False, max_length=120, null=True),
        ),
    ]
