# Generated by Django 3.0.8 on 2020-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0032_auto_20201020_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submited_assignment',
            name='student_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
