# Generated by Django 3.0.8 on 2020-10-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0037_auto_20201020_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submited_assignment',
            name='result',
            field=models.IntegerField(default=None),
        ),
    ]
