# Generated by Django 4.2.1 on 2023-10-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtoschool', '0043_delete_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submited_assignment',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('English', 'English'), ('Civics', 'Civics'), ('ICT', 'ICT')], max_length=120, null=True),
        ),
    ]
